language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - CI=false npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: pm3.surge.sh
  project: ./build/
on:
  branch: master